experiment_name: expB4_phase_gate_focal
seed: 2025
metadata_path: metadata/combined_metadata.json
sample_rate: 4000
max_duration: 20.0
max_locations: 4
train:
  batch_size: 2
  num_epochs: 45
  learning_rate: 3.0e-4
  weight_decay: 0.01
  warmup_epochs: 3
  mixed_precision: "bf16"
  gradient_accumulation_steps: 6
  label_smoothing: 0.0
  contrastive_weight: 0.0
  contrastive_temperature: 0.3
  unfreeze_backbone_at_epoch: 5
  loss_type: focal
  focal_gamma: 2.0
  focal_alpha_balanced: true
model:
  hidden_dim: 256
  state_dim: 128
  depth: 4
  num_heads: 4
  dropout: 0.1
  metadata_dim: 64
  waveform_backbone: /map-vepfs/qinyu/CodeSpace/HeartSound/hf_cache/models/wavlm-base-plus
  backbone_sample_rate: 16000
  freeze_backbone: true
  phase_gating: true
  phase_kernel: 15
  phase_strength: 0.6
scheduler:
  max_epochs: 45
  min_lr: 1.0e-6
logging:
  output_dir: runs
  checkpoint_interval: 1

